package cli

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/DesmondSanctity/shipnote/internal/config"
	"github.com/DesmondSanctity/shipnote/internal/repo"
)

// defaultConfigBody is the file written by `shipnote init`. It is
// intentionally a complete template (not just defaults) so users can
// see every supported key and uncomment what they need.
const defaultConfigBody = `# .shipnote.toml — generated by ` + "`shipnote init`" + `
# https://github.com/DesmondSanctity/shipnote

[repo]
provider = "github"
owner    = "%s"
name     = "%s"

[packages]
mode = "single"
# root = "your-package-id"

[output]
markdown = "CHANGELOG.md"
json     = ".shipnote/release.json"

[ignore]
authors = ["dependabot[bot]", "renovate[bot]"]
labels  = ["skip-changelog"]
# paths = []

# Author identity merging — sum changes across login aliases.
# [[authors]]
# canonical = "alice"
# aliases   = ["alice@example.com", "Alice"]
# name      = "Alice"
# url       = "https://github.com/alice"
`

const prTemplateSnippet = `

<!-- shipnote -->
### Changelog

<!-- One of: feat, fix, perf, security, deprecation, docs, refactor, build, ci, test, chore. -->
<!-- Add ` + "`!`" + ` after the type for a breaking change, e.g. ` + "`feat!`" + `. -->
<!-- Leave the body empty to suppress this PR from the changelog. -->

` + "```changelog\n```\n"

func runInit(cmd *cobra.Command, _ []string) error {
	yes := boolFlag(cmd, "yes")
	force := boolFlag(cmd, "force")
	withTpl := boolFlag(cmd, "with-pr-template")

	root, err := resolveRepoRoot()
	if err != nil {
		return err
	}
	cfgPath := config.ResolvedPath(root, "")

	owner, name := detectOwnerName(cmd, root)

	if _, err := os.Stat(cfgPath); err == nil && !force {
		return fmt.Errorf("%s already exists; pass --force to overwrite", cfgPath)
	} else if err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("stat %s: %w", cfgPath, err)
	}

	if !yes {
		_, _ = fmt.Fprintf(cmd.OutOrStdout(),
			"shipnote: writing %s for %s/%s\n", cfgPath, owner, name)
	}

	body := fmt.Sprintf(defaultConfigBody, owner, name)
	if err := os.WriteFile(cfgPath, []byte(body), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", cfgPath, err)
	}

	if err := ensureGitignoreEntry(root, ".shipnote/"); err != nil {
		return err
	}

	if withTpl {
		if err := appendPRTemplate(root); err != nil {
			return err
		}
	}

	_, _ = fmt.Fprintf(cmd.OutOrStdout(), "shipnote: initialized\n")
	return nil
}

func detectOwnerName(cmd *cobra.Command, root string) (string, string) {
	g, err := repo.Open(cmd.Context(), root)
	if err != nil {
		return "auto", "auto"
	}
	u, err := g.OriginURL(cmd.Context())
	if err != nil || u == "" {
		return "auto", "auto"
	}
	owner, name, ok := repo.ParseGitHubRemote(u)
	if !ok {
		return "auto", "auto"
	}
	return owner, name
}

func ensureGitignoreEntry(root, entry string) error {
	path := filepath.Join(root, ".gitignore")
	existing, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return os.WriteFile(path, []byte(entry+"\n"), 0o644)
	}
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	for _, line := range strings.Split(string(existing), "\n") {
		if strings.TrimSpace(line) == entry {
			return nil
		}
	}
	body := string(existing)
	if !strings.HasSuffix(body, "\n") {
		body += "\n"
	}
	body += entry + "\n"
	return os.WriteFile(path, []byte(body), 0o644)
}

func appendPRTemplate(root string) error {
	dir := filepath.Join(root, ".github")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	path := filepath.Join(dir, "pull_request_template.md")
	existing, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return os.WriteFile(path, []byte(strings.TrimLeft(prTemplateSnippet, "\n")), 0o644)
	}
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	if strings.Contains(string(existing), "<!-- shipnote -->") {
		return nil
	}
	body := string(existing)
	if !strings.HasSuffix(body, "\n") {
		body += "\n"
	}
	body += prTemplateSnippet
	return os.WriteFile(path, []byte(body), 0o644)
}
